version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    environment:
      JENKINS_OPTS: '--httpPort=18080'
    ports:
      - 18080:18080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
